#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

module load R/3.3.1-intel-2016b

# setting temporary directory

export TMPDIR=~/qiime_tmp

time compare_categories.py —method anosim -i ~/2018_02_smb/CDA_AcidoProteo/bdiv_even601/unweighted_unifrac_dm.txt -m ~/2018_02_smb/map.tsv -c SamplePh -o Compare_Categories_ANOSIM 


#deactivate

source deactivate
