#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

echo "comparing alpha diversity"

time compare_alpha_diversity.py -i ~/2018_02_smb/CDA_AcidoProteo/arare_max601/alpha_div_collated/PD_whole_tree.txt -m ~/2018_02_smb/map.tsv -c SamplePh -t nonparametric -o AP_Compare_Alpha_Div__pH

source deactivate
