#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

#core diversity analysis 

echo "analysing core diversity"
time core_diversity_analyses.py -i ~/2018_02_smb/OTU_Table_Filtered_By_Sample.biom  -m ~/2018_02_smb/map.tsv -c SamplePh -o CDA -e 33549 --recover_from_failure -t ~/2018_02_smb/OTUs/97_otus.tree

#deactivate

source deactivate
