#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

#group significance pH 

time group_significance.py -i ~/2018_02_smb/CDA_AcidoProteo/taxa_plots_SamplePh/SamplePh_otu_table_sorted_L3.biom -m ~/2018_02_smb/map.tsv -c SamplePh -o Group_Significance_pH_AcidoProteo_Classes.txt

#deactivate

source deactivate
